name: build
on:
  push:
  workflow_dispatch:
jobs:
  build-m5dial-simple-pointer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build
        run:
          cd m5dial-simple-pointer;
          cp ssid.h.template ssid.h;
          pio run
